name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Uses your FIREBASE_TOKEN secret and firebase.json/.firebaserc
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}       # allows PR comments; harmless on push to main
          firebaseToken: ${{ secrets.FIREBASE_TOKEN }} # you already have this secret
          projectId: gp-member-portal
          channelId: live
